<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="layout" tagdir="/WEB-INF/tags" %>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>

<layout:main pageTitle="AI Generated Questions">

<div class="d-flex align-items-center justify-content-between mb-4">
    <p class="text-muted mb-0" style="font-size: 13px;">Questions generated by AI for moderators. Use <code>POST /api/ai/suggest-questions</code> to generate more.</p>
</div>

<div class="lucy-table">
    <c:choose>
        <c:when test="${empty questions}">
            <div class="empty-state">
                <i class="bi bi-chat-dots"></i>
                <p>No AI questions yet. Use the API or Swagger UI to generate questions.</p>
                <a href="/swagger-ui/index.html" target="_blank" class="btn btn-outline-lucy btn-sm mt-2"><i class="bi bi-braces me-1"></i> Open Swagger</a>
            </div>
        </c:when>
        <c:otherwise>
            <table class="table mb-0">
                <thead>
                    <tr><th>ID</th><th>Type</th><th>Question</th><th>Lesson</th><th>Used</th><th>Generated</th><th style="width:100px;">Actions</th></tr>
                </thead>
                <tbody>
                    <c:forEach var="q" items="${questions}">
                        <tr>
                            <td><strong>#${q.id}</strong></td>
                            <td><span class="badge-status badge-purple">${q.promptType}</span></td>
                            <td style="max-width: 400px;">${q.generatedQuestion}</td>
                            <td><c:if test="${q.lesson != null}">${q.lesson.title}</c:if></td>
                            <td>
                                <a href="/ai-generated-questions/toggle-used/${q.id}" style="text-decoration: none;">
                                    <c:choose>
                                        <c:when test="${q.usedByModerator}"><span class="badge-status badge-success">Used</span></c:when>
                                        <c:otherwise><span class="badge-status badge-gray">Unused</span></c:otherwise>
                                    </c:choose>
                                </a>
                            </td>
                            <td style="font-size: 12px;">${q.generatedAt}</td>
                            <td>
                                <button class="btn-action delete" onclick="confirmDelete('/ai-generated-questions/delete/${q.id}')"><i class="bi bi-trash"></i></button>
                            </td>
                        </tr>
                    </c:forEach>
                </tbody>
            </table>
        </c:otherwise>
    </c:choose>
</div>

</layout:main>
