<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="layout" tagdir="/WEB-INF/tags" %>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>

<layout:main pageTitle="AI Generated Questions">

<div class="d-flex align-items-center justify-content-between mb-4">
    <p class="text-muted mb-0" style="font-size: 13px;">Questions generated by AI for moderators.</p>
</div>

<!-- Generate Questions Form -->
<div class="stat-card mb-4">
    <h6 style="font-weight: 600; margin-bottom: 16px;"><i class="bi bi-stars me-1"></i> Generate New Questions</h6>
    <div class="row g-3 align-items-end">
        <div class="col-md-4">
            <label class="form-label" style="font-size: 12px;">Lesson</label>
            <select id="aiLessonId" class="form-select form-select-sm">
                <option value="">— Select a Lesson —</option>
                <c:forEach var="l" items="${allLessons}">
                    <option value="${l.id}">[${l.type}] ${l.title}</option>
                </c:forEach>
            </select>
        </div>
        <div class="col-md-3">
            <label class="form-label" style="font-size: 12px;">Prompt Type</label>
            <select id="aiPromptType" class="form-select form-select-sm">
                <option value="discussion">Discussion</option>
                <option value="warmup">Warmup</option>
                <option value="ice_breaker">Ice Breaker</option>
                <option value="practice">Practice</option>
                <option value="wrapup">Wrap Up</option>
            </select>
        </div>
        <div class="col-md-3">
            <button id="btnGenerateAi" class="btn btn-lucy btn-sm w-100" onclick="generateAiQuestions()">
                <i class="bi bi-stars me-1"></i> Generate AI Questions
            </button>
        </div>
    </div>

    <!-- Loading -->
    <div id="aiLoading" class="text-center mt-3" style="display: none;">
        <div class="spinner-border spinner-border-sm text-primary" role="status"></div>
        <span style="font-size: 13px; margin-left: 8px;">Generating questions with AI...</span>
    </div>

    <!-- Inline Result -->
    <div id="aiResults" class="mt-3" style="display: none;">
        <div class="d-flex align-items-center gap-2 mb-2">
            <span style="font-size: 13px; font-weight: 600; color: #059669;"><i class="bi bi-check-circle me-1"></i> Generated successfully!</span>
            <span id="aiMockBadge" class="badge-status badge-warning" style="font-size: 11px; display: none;">Mock Mode</span>
        </div>
        <ul id="aiQuestionList" style="padding-left: 18px; font-size: 13px;"></ul>
        <a href="/ai-generated-questions" class="btn btn-outline-lucy btn-sm mt-2"><i class="bi bi-arrow-clockwise me-1"></i> Refresh Page</a>
    </div>

    <!-- Error -->
    <div id="aiError" class="mt-3" style="display: none;">
        <div class="text-danger" style="font-size: 13px;"><i class="bi bi-exclamation-triangle me-1"></i> <span id="aiErrorMsg"></span></div>
    </div>
</div>

<div class="lucy-table">
    <c:choose>
        <c:when test="${empty questions}">
            <div class="empty-state">
                <i class="bi bi-chat-dots"></i>
                <p>No AI questions yet. Use the API or Swagger UI to generate questions.</p>
                <a href="/swagger-ui/index.html" target="_blank" class="btn btn-outline-lucy btn-sm mt-2"><i class="bi bi-braces me-1"></i> Open Swagger</a>
            </div>
        </c:when>
        <c:otherwise>
            <table class="table mb-0">
                <thead>
                    <tr><th>ID</th><th>Type</th><th>Question</th><th>Lesson</th><th>Used</th><th>Generated</th><th style="width:100px;">Actions</th></tr>
                </thead>
                <tbody>
                    <c:forEach var="q" items="${questions}">
                        <tr>
                            <td><strong>#${q.id}</strong></td>
                            <td><span class="badge-status badge-purple">${q.promptType}</span></td>
                            <td style="max-width: 400px;">${q.generatedQuestion}</td>
                            <td><c:if test="${q.lesson != null}">${q.lesson.title}</c:if></td>
                            <td>
                                <a href="/ai-generated-questions/toggle-used/${q.id}" style="text-decoration: none;">
                                    <c:choose>
                                        <c:when test="${q.usedByModerator}"><span class="badge-status badge-success">Used</span></c:when>
                                        <c:otherwise><span class="badge-status badge-gray">Unused</span></c:otherwise>
                                    </c:choose>
                                </a>
                            </td>
                            <td style="font-size: 12px;">${q.generatedAt}</td>
                            <td>
                                <button class="btn-action delete" onclick="confirmDelete('/ai-generated-questions/delete/${q.id}')"><i class="bi bi-trash"></i></button>
                            </td>
                        </tr>
                    </c:forEach>
                </tbody>
            </table>
        </c:otherwise>
    </c:choose>
</div>

<script>
function generateAiQuestions() {
    var lessonId = document.getElementById('aiLessonId').value;
    var promptType = document.getElementById('aiPromptType').value;

    if (!lessonId) {
        alert('Please select a lesson first!');
        return;
    }

    var btn = document.getElementById('btnGenerateAi');
    var loading = document.getElementById('aiLoading');
    var results = document.getElementById('aiResults');
    var errorDiv = document.getElementById('aiError');

    btn.disabled = true;
    loading.style.display = 'block';
    results.style.display = 'none';
    errorDiv.style.display = 'none';

    fetch('/api/ai/suggest-questions?lessonId=' + lessonId + '&promptType=' + promptType, {
        method: 'POST'
    })
    .then(function(response) { return response.json(); })
    .then(function(data) {
        loading.style.display = 'none';
        btn.disabled = false;

        if (data.message) {
            errorDiv.style.display = 'block';
            document.getElementById('aiErrorMsg').textContent = data.message;
            return;
        }

        results.style.display = 'block';
        var mockBadge = document.getElementById('aiMockBadge');
        mockBadge.style.display = data.isMock ? 'inline' : 'none';

        var list = document.getElementById('aiQuestionList');
        list.innerHTML = '';
        if (data.questions) {
            data.questions.forEach(function(q) {
                var li = document.createElement('li');
                li.style.marginBottom = '6px';
                li.textContent = q.generatedQuestion || q;
                list.appendChild(li);
            });
        }
    })
    .catch(function(err) {
        loading.style.display = 'none';
        btn.disabled = false;
        errorDiv.style.display = 'block';
        document.getElementById('aiErrorMsg').textContent = 'Failed to connect: ' + err.message;
    });
}
</script>

</layout:main>
